### ISSUE TITLE
Request to upgrade app to support Python 3

### ISSUE THREAD

**Issue by ShubhankarKulkarni** [georgestarcher/TA-esreplacefields#1]
Hi @georgestarcher,

We use this app in our Splunk environment. Since this add-on was built way back, it started showing up in the Python 3 incompatible add-ons list that needs a refresh to continue to work with newer versions of Splunk Enterprise. Will it be possible for you to get this add-on upgraded to support Python 3 or suggest any alternative methods to make this version work with Splunk Enterprise 8.2+.

Thanks
Shubhankar Kulkarni
Lumen Technologies

**Comment by georgestarcher** [comment]
This is deprecated. You should not be using it when Splunk added expandtoken command few years ago.
